### ISSUE TITLE
If you are on one of these platforms and are seeing this then either JavaScript is disabled or this website is drunk and should be reported.

### ISSUE THREAD

**Issue by vi** [rust-lang-nursery/rustup.rs#267]
User-Agent: Mozilla/5.0 (X11; Linux i686 on x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by brson** [comment]
Thanks for the report! Am I correct that you *don't* have JavaScript disabled?

[Here's the platform detection code](https://github.com/rust-lang-nursery/multirust-rs/blob/master/www/rustup.js#L1). Since you are on Linux I'd expect either `navigator.platform` or `navigator.appVersion` to contain the word 'Linux'. Would you mind printing the values of these in the JS console and pasting them here?

**Comment by brson** [comment]
Also, I'd be curious if you see the correct binary download link on https://www.rust-lang.org/, or if it gives you the generic source link.

**Comment by vi** [comment]
The message persisted even after I allowed the domain in NoScript and reloaded the page.

**Comment by vi** [comment]
Checked again with cleander Firefox profile: the same.

```
navigator.appVersion
"5.0 (X11)"
navigator.platform
"Linux i686 on x86_64"
```

**Comment by vi** [comment]
In any case there should also be manual platform specifier, some "universal mode", etc.

On Android I see the `curl ...` line if I open http://rustup.rs with build-in browser, but it fails if I open it with Firefox.

**Comment by brson** [comment]
OK, I see where your values differ from what the script expects. I'm going to be hacking on the website this week and will try to get this resolved.
