### ISSUE TITLE
tab completions

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#278]
> I've been using it for almost a week and seems great! I only miss tab completions, that would be awesome :slight_smile: thanks Brian!

Hm, after thinking about this further, tab completions are going to be tricky. rustup does not require root to install but completions are usually installed to /etc. I really don't want to require admin just for that. I wonder if we might further frob the shell startup files (like we already to to modify PATH) to load completions.

[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/54?u=brson).

**Comment by japaric** [comment]
>  I wonder if we might further frob the shell startup files (like we already to to modify PATH) to load completions.

FWIW, in my case I use `zsh` and I enable the `cargo` auto completions (that `rustup` installs) without touching the `/etc` directory by modifying the `fpath` variable in my `zshrc` as shown [here](https://github.com/japaric/.dotfiles/blob/4a5cdd594fcee65ad5030eb1c56945d13df2301b/.zshrc#L19). I also use the oh-my-zsh framework and I've noticed that I need to modify the `fpath` variable before sourcing the oh-my-zsh framework.

Disclaimer: I don't really grok zsh internals and perhaps there is a way to enable `cargo` autocompletions after the oh-my-zsh framework has been loaded.

P.S. I don't really like that CLI tools modify my zshrc, I usually undo/modify what they do :smile:. I would be happy if `rustup` just installs a `_rustup` completion file somewhere in the `.multirust` folder like it does with `_cargo`.

**Comment by kbknapp** [comment]
@brson  @japaric 

I've just added the ability to [generate bash completions](http://kbknapp.github.io/clap-rs/clap/struct.App.html#method.gen_completions) for a cli with `clap` at compile time. Here's a gist of the [generated completion script](https://gist.github.com/kbknapp/09a37f2fce306573040ea0500e3b1408) for `rustup`

And a demo:

![rustup_compl](http://i.imgur.com/icbrIYe.gif)

[I have a branch on my fork](https://github.com/kbknapp/multirust-rs/tree/bash_compl) where I generated the completions, although before I'd put in a PR there are few opinionated portions that I'd rather a project maintainer look at prior

 * having to move the `rustup_mode::cli` function into a separate file in order to include via the `build.rs`. 
 * there's a strange issue where I couldn't `use help::*;` from `rustup_app.rs` so I had to `include!` it.
 * finally, the output of the completion script goes to  `OUT_DIR`

Granted this is only a Bash completion script, but it's at least a step in *a* direction (if it's the *right* direction is TBD). I personally use ZSH, so that's next on my list.

**Comment by Diggsey** [comment]
@kbknapp Wow, that's awesome!

**Comment by wuranbo** [comment]
go go go

**Comment by brson** [comment]
@kbknapp Sweet! That's really clever.

I'm fine doing the conversion, but I'd still like to wait until we understand how to install them before pulling trigger.

**Comment by knight42** [comment]
@kbknapp Any progress now? It's a pain to me when auto-completion is unable to use.

**Comment by kbknapp** [comment]
@knight42 I haven't added ZSH support yet. Once I do I'll post back here.

**Comment by knight42** [comment]
@kbknapp Great! It's better to generate the completion script automatically. I am looking forward to it!

**Comment by kbknapp** [comment]
@knight42 

I've just added ZSH support to `clap` (finally! :tada:), and put in a PR to `rustup` to add it. The PR also includes Bash, and Fish support as well.

Here's a gif of the ZSH support though:

![rustup_zsh](https://cloud.githubusercontent.com/assets/6942134/19633497/625dd8b0-9980-11e6-8346-a56ca42fab5f.gif)

**Comment by knight42** [comment]
@kbknapp Awesome, love it!

**Comment by est31** [comment]
Thanks for the autocompletion feature @kbknapp I really like it!

Would it be possible to extend the tab completion support to include things rustup can derive? Like when you type `rustup override add<TAB><TAB>` it should give you a list of toolchains.

Its obviously more complicated, but should be doable, no?

flatpak manages to do this btw, you can press `flatpak run org.app.<TAB>` and it will autocomplete the app name.

**Comment by kbknapp** [comment]
@est31 not yet, but that is the exact topic of kbknapp/clap-rs#568

**Comment by kbknapp** [comment]
I should add you can do this manually, but it's not built in to clap yet :will:

**Comment by Diggsey** [comment]
I think this can be considered complete?
