### ISSUE TITLE
Remove `multirust` bin from installation

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#284]
Right now rustup installs both `rustup` and `multirust`. Stop distributing the latter.

**Comment by fish-ter** [comment]
I just received a distribution of `multirust`, after installing `rustup` for the first time, using the `curl https://sh.rustup.rs -sSf | sh` instructions found at rustup.rs. I can see both a multirust executable in `~/.cargo/bin`and a `~/.multirust` tree to accompany it.

Is my experience consistent with the reason this issue was closed?
