### ISSUE TITLE
handle install failures better

### ISSUE THREAD

**Issue by rusty-new-dev** [rust-lang-nursery/rustup.rs#32]
Right now, if a toolchain install fails (for example, if the msi server was not running, or one was running multirust in an account without the needed permissions to make installations), one has to start the process all over again. This isn't too bad, except for the case where one has a slow network connection (take hours to download) and the installer was downloaded by multirust (not obvious where to find the downloaded installer file, assuming it still exists somewhere on the the machine). Would be nice to have either some way of retrying the install or a way to download and save the installers somewhere, waiting for the user to install manually (some might like the latter better as it allows them to run multirust with less privileges when downloading the installers).

**Comment by Diggsey** [comment]
I've been meaning to get around to implementing something like this for a while, it's just a little tricky to get right without leaving unnecessary files lying around. Thanks for creating an issue.

**Comment by mackwic** [comment]
Yes ! :+1: to this issue !

> it's just a little tricky to get right without leaving unnecessary files lying around.
What about a journal ? A simple flat text with the last events since the last successful execution, so failures don't reset the journal. This shouldn't be more than a few kilobytes.

When using `multirust update stable --continue`, the journal keep trace of the useful files created by the precedent failed executions (could be a crash, a SIGINT, whatever). If no `--continue`, simply trim the journal and log the execution.
