### ISSUE TITLE
Add a --yes option to avoid using /dev/tty

### ISSUE THREAD

**Issue by tomaka** [rust-lang-nursery/rustup.rs#327]
Running `curl https://sh.rustup.rs -sSf | sh` on gitlab CI's infrastructure (which uses docker) results in:

> sh: 59: cannot open /dev/tty: No such device or address

(for some reason the check at line 55 doesn't work)

Multirust (the non-Rust one) had a `--yes` option that allows it to avoid using /dev/tty. It would be nice if that option was in rustup too.

**Comment by japaric** [comment]
#325 added an `-y` option (that skips the y/n prompt) to the shell script but it seems the script on the website hasn't been updated yet (cc @brson, when is that script re-deployed? my guess would be: when master gets merged into stable)

I think #325 may not be enough in the case of Docker containers because /dev/tty would still be open even when there is no prompt. If that's the case the issue would be fixed by some extra logic in the shell script. I'll look into it.

> (for some reason the check at line 55 doesn't work)

My guess is that the file does exists but error is caused because of lack of permissions (i.e. `docker` was called without `--privileged`).

**Comment by brson** [comment]
@japaric The script is redeployed when publishing to stable, yes. The script has recently been renamed to rustup-init.sh, and the website not updated to reflect that. I'll make that update now.

**Comment by brson** [comment]
Oh, right. I've updated the win.rustup.rs and sh.rustup.rs proxy rules to deliver rustup-init.exe and rustup-init.sh instead of rustup-setup.

And it's still not delivering the updated script. I'm looking into it.

**Comment by brson** [comment]
Updated script is deployed.
