### ISSUE TITLE
Not usable for bootstrapping the Rust compiler

### ISSUE THREAD

**Issue by nodakai** [rust-lang-nursery/rustup.rs#357]
When src/stage0.txt has `rustc: beta-2016-04-13`, `rustup update beta-2016-04-13` should be usable for bootstrapping the Rust compiler with the following `configure`: 

```
$ ./configure --enable-local-rust --local-rust-root=$HOME/.cargo
```

But `rustc` from `rustup` doesn't look into, say, `rust-HEAD/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib` and the compilation fails when, say, `rust-HEAD/src/libcollection` depends on a newly introduced function in, say, `rust-HEAD/src/libcore`.

This is a somewhat ugly workaround:

```
$ ./configure --enable-local-rust --local-rust-root=$HOME/.multirust/toolchains/beta-2016-04-13-x86_64-unknown-linux-gnu
```

**Comment by brson** [comment]
From the description I'm not sure what's going on here, but I'm not sure I'd *expect* `--local-rust-root` to work when pointing to `~/.cargo/`. The `--local-rust-root` command might instead be called `--local-rust-sysroot`.

On the other hand, there's probably a simple fix in rustc's build system to make this work: instead of passing the sysroot to configure, just have configure ask `rustc` for the sysroot with `--print sysroot` (or whatever it is); change the `configure` option to `--local-rustc` / `--local-cargo` etc.


cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah this doesn't look like a bug on rustup, but perhaps an extension for the configure script
