### ISSUE TITLE
Stable channel not available for FreeBSD?

### ISSUE THREAD

**Issue by mwm** [rust-lang-nursery/rustup.rs#381]
Well, rustup is installed and apparently working, but can't update the stable channel. Trying `rustup update stable` results in:

> info: syncing channel updates for 'stable-x86_64-unknown-freebsd'
> error: some components unavailable for download: 'rustc', 'rust-std', 'rust-docs', 'cargo'

`rustup update nightly` worked, so I believe my rustup install is working properly.

The rust stable build (1.8.0) is available in the system packages. I can't seem to find a way to use those binaries from rustup, meaning I can't use it t install the bits for cross-compilation, which is my end goal.

**Comment by japaric** [comment]
> Stable channel not available for FreeBSD?

It's not available due to infrastructure changes not making it in time for 1.8.0. But the freebsd stable channel will by available by 1.9.0.

> The rust stable build (1.8.0) is available in the system packages. I can't seem to find a way to use those binaries from rustup

Yeah, I think is not possible to override the stable channel with a custom toolchain. Even if that worked, you probably would hit rust-lang/rust#33286 afterwards :-/.

> meaning I can't use it t install the bits for cross-compilation, which is my end goal.

I would suggest using the beta or nightly channel until the next release.

**Comment by mwm** [comment]
Yes, I did indeed hit that issue. I worked around that by building the package with a git extract of 1.8.0 instead of the tarball extract. Worked fine, but I still can't use rustup because it can't deal with toolchains it didn't install.

I'm trying to convince people running embedded software controlling hundreds or thousands of dollars worth of their hardware that a control failure could turn into a bag of refuse to start converting parts of it to Rust. It's also possible for such failures to cause serious bodily harm. The negative implications of "beta" or "nightly" software are going to make that very difficult, if not impossible, no matter what the reality is. It makes the frequency that I run into "just use the beta/nightly" as an answer to my issues with Rust frustrating, and may well kill the project.

**Comment by kbknapp** [comment]
Getting `multirust`/`rustup` with stable on FreeBSD has been something I've been waiting for a while now. In general, without `rustup`, stable was already working on FreeBSD, no? If that's the case, could the stable release channel not just move back to the latest working stable? I know this isn't optimal, but if the stable channel simply resulted in 1.7 instead of 1.8 in this one particular case I'd still be happy.

**Comment by brson** [comment]
@kbknapp The next release is at least not too far off, on the 26th.

**Comment by Diggsey** [comment]
Issues like this should probably be reported upstream in rust-lang/rust, because rustup doesn't build the manifests.
