### ISSUE TITLE
--default-toolchain only accepts "stable", "beta", and "nightly"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#437]
@brson though it accepted "beta-x86_64-pc-windows-msvc", which would also be nice!

**Comment by brson** [comment]
There's a small downside to this in that the user may pick a bogus toolchain, then we have to deal with that somehow.

**Comment by kbknapp** [comment]
You could use a [validator](http://kbknapp.github.io/clap-rs/clap/struct.Arg.html#method.validator), perhaps with some sort of regex? There's also the possibility of just hard coding all the toolchains like the "stable", "beta", "nightly" is now, but then [hiding those values from the help output](http://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html#variant.HidePossibleValuesInHelp) since it'd be so long. The downside with hiding the values is it'd hide all "possible values" for all of `rustup-init` or whatever the parent command/subcommand is (although at present, there are no other possible values besides `--default-toolchain`). Just thinking out loud.

**Comment by brson** [comment]
Thanks for the suggestions @kbknapp.

I think though I'd prefer for this bug to just ask forgiveness when the installation fails - the error handling around failed toolchain installation during the initial install needs to be robust anyway.

This is fixed on master.
