### ISSUE TITLE
unknown metadata version

### ISSUE THREAD

**Issue by fenhl** [rust-lang-nursery/rustup.rs#453]
Trying to install rustup on a system that previously had multirust.sh installed, I get the following error:

```
$ rustup self upgrade-data
info: upgrading metadata version from '1' to '12'
error: unknown metadata version: '1'
```

**Comment by pnkfelix** [comment]
I saw this as well.

Executive summary: If you want to get things working quickly, you might try deleting (or renaming) `~/.multirust` and re-running `rustup`.

----

Some quick notes about what I'm seeing:

 1. I wasn't sure if I was going to commit to migrating from `multirust` to `rustup`, so rather than delete `~/.multirust` as advised by the installer, I instead renamed that directory to `~/.multirust.old`

 2. I then followed the installation procedure, running `curl https://sh.rustup.rs -sSf | sh`, and letting it do the update to `~/.profile`. I also did `source `~/.cargo/env` to update my current `PATH` in the terminal session. (However, I now remember that one or two times I may have terminated the installation early via Ctrl-C and restarted it later; its possible that is somehow related to the bug.)

 3. Once the installation was complete, running commands like `rustc` yielded errors like:
> error: rustup's metadata is out of date. run `rustup self upgrade-data`
Which is what led me to attempt to run the `upgrade-data` command, yielding the error in the description.

 4. I subsequently discovered that by renaming the `~/.multirust` that had been generated via the installation, a subsequent invocation of any of the commands like `rustc` caused `multirust` to generate a new `~/.multirust/` directory with a single file, `~/.multirust/version`, that just contained the text `12`.

At this point, `rustup self upgrade-data` works.

**Comment by brson** [comment]
rustup legitimately doesn't support upgrading from the (old) metadata version `1`, but the workflow described here is horrible.

I suspect that some of the defensive measures added to `rustup-init` will prevent this happening in the future. Now it should tell you to delete anything resembling old multirust before trying to install.
