### ISSUE TITLE
Don't show targets in toolchain names by default in the UI

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#461]
I had an issue about this before but lost it.

I've seen people confused that they should be installing `stable-$target` to do cross-compiling. For the most part the host architecture doesn't matter. If you care about the host architecture it will be set as in https://github.com/rust-lang-nursery/rustup.rs/pull/421 and reported in `rustup show`. We don't need to say it all the time.

Not showing target names in toolchain names makes it more obvious that you generally use target triples to specify targets, not toolchains.

So everywhere the UI shows e.g. `stable-x86_64-unknown-linux-gnu` it will instead say `stable`. Unless the toolchain's target is not the same as the default host per #421, or the user actually requested a different target explicitly.

@nrc This is related to some of the question you had today. The distinction between the host and target platform is a fairly confusing topic.

cc @alexcrichton @Diggsey

**Comment by brson** [comment]
On the other hand, we could also unify the idea of toolchains and targets and make `stable-$any-target` just work.

**Comment by Diggsey** [comment]
I agree with hiding the host triple portion of the toolchain name when it matches the configured host.

I don't think we should unify the idea of toolchains and targets, because 1) it does have some uses, 2) there are still some subtle differences between a rustc with host X, target Y and a rustc with host Y, target Y, 3) it's potentially even more confusing, if only because it's a much further from what's actually happening, and 4) it would take quite a while to get rustup relatively stable again after such a massive change.

I think the solution is to de-emphasise the use of toolchains, introducing it purely as a means to switch between release channels and versions, and not introduce toolchain-triple switching at that point. In combination with hiding the triple this should simplify basic usage.

It may also be worth moving the `override` and `default` subcommands into the `toolchain` subcommand (with undocumented aliases for back-compat) in case we want to add `target` overrides too at some later time, which we can do at our leisure, without compromising the rest of the functionality. (Also people who don't want rustup to start messing with their compile flags can just avoid using that functionality)

**Comment by Diggsey** [comment]
Found it: #351
