### ISSUE TITLE
Installer shows extra blank lines on Windows 7

### ISSUE THREAD

**Issue by kraai** [rust-lang-nursery/rustup.rs#525]
When I run rustup-init.exe on my Windows 7 system, there are a number of extra blank lines:

* Between "This path will then be added to your PATH environment variable by modifying the" and "HKEY_CURRENT_USER/Environment/PATH registry key."
* Between "You can uninstall at any time with rustup self uninstall and these changes will" and "be reverted."
* ...

![rustup wrapping](https://cloud.githubusercontent.com/assets/552646/15968665/44f5a2cc-2f1c-11e6-806a-4637c2104ce7.png)

It appears that if a character (including a space) is written to the last column, a blank link will be displayed.

**Comment by Diggsey** [comment]
@kraai `rustup` wraps at the 80 character limit, but your terminal is size to 79 characters wide, resulting in double wrapping (the windows terminal since about windows 7 acts as a virtual "infinitely wide" terminal which is then wrapped to the current terminal width).

There's currently no portable way to determine the terminal width from rust, but if there were we could use that as the margin size instead.

**Comment by kraai** [comment]
@Diggsey I'm pretty sure the window is 80 characters wide: "Future applications will automatically have the correct environment, but you may" is 80 characters and it's shown on exactly one line.

Since I think this is the default Command Prompt window width, it may be worth handling a little better.

**Comment by Diggsey** [comment]
Ah yes, it seems like `cmd` wraps on the 80th character rather than waiting until the 81st character. We should be able to just change the margin to `79` characters to fix the problem.
