### ISSUE TITLE
Print new version while `rustup self update`

### ISSUE THREAD

**Issue by liigo** [rust-lang-nursery/rustup.rs#542]
before or after update complete.

**Comment by brson** [comment]
I've been indecisive about this. I originally didn't do this because I wanted the rustup version to not be important - it's just continually updated. And with `rustup upgrade` I think the version of *Rust* is the most important thing - the version of rustup is not as interesting.

These are the outputs for the two types of updates today

```
brian@ip-10-145-43-250:~/dev/rustup.rs⟫ rustup self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully
brian@ip-10-145-43-250:~/dev/rustup.rs⟫ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates
info: rustup is up to date

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.9.0 (e4e8b6668 2016-05-18)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.10.0-beta.2 (39f3c16cc 2016-05-26)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.11.0-nightly (5522e678b 2016-06-20)
```

Maybe the rustup version could be put on the info log line that mentions the update: "rustup successfully updated to X.Y.Z" . That way with `self update` it's on the last line, but with `update` the information is displayed but doesn't distract from the more important toolchain info.

**Comment by liigo** [comment]
"rustup successfully updated to X.Y.Z" is nice to have.

**Comment by brson** [comment]
OK, let's change the "rustup updated successfully" message to "rustup successfully updated to X.Y.Z". Getting the version will require running the newly-downloaded bin.

**Comment by julienXX** [comment]
Hi I'd like to try to tackle this issue if nobody is already working on it.

**Comment by brson** [comment]
@julienXX You got it!

**Comment by brson** [comment]
@julienXX How's it going?

**Comment by julienXX** [comment]
@brson sorry been very busy these days but I still intend to submit a PR hopefully in the next few days.

**Comment by julienXX** [comment]
@brson I've submitted #614 but I'm not sure it's the best way to fix it. What do you think about it?

**Comment by brson** [comment]
Thanks @julienXX ! I added a comment on the PR.
