### ISSUE TITLE
rustup-init will install to %USERPROFILE%/.cargo on windows, even if run from msys2/mingw64 prompt

### ISSUE THREAD

**Issue by sekhat** [rust-lang-nursery/rustup.rs#546]
I'm attempting to run rustup-init.exe, as obtained via any of the windows version of rustup-init, from an msys2/mingw shell and it will always set my default install path to `%USERPROFILE%\.cargo`

However, I have a separate `HOME` folder when running from msys2/mingw shell and I'd prefer it to install at `$HOME/.cargo`

However, there seems to be no way to override the install path. Even copying and renaming `rustup-init` to `~/.cargo/bin/rustup` and setting the `RUSTUP_HOME` environment variable to `~/.cargo/`, it appears to still expect rustup to be in `%USERPROFILE%\.cargo`

**Comment by Diggsey** [comment]
The first part is intentional (using userprofile directory from msys by default) - without it, rustup installed via the installer would be unusable from within the msys terminal, whereas in a typical setup, the programs available to the msys terminal is a superset of those on the windows command line.

However, you should be able to override the rustup directory within the msys terminal by setting the `RUSTUP_HOME` environment variable. If that doesn't work it's a bug.

ooi, do you have a particular reason for wanting two separate rustup installations?

**Comment by sekhat** [comment]
Ah no, I just want one install, it's just that I want it in my MSYS2 $HOME/.cargo directory, instead of my windows user profile directory.

**Comment by brson** [comment]
If you are willing to jump through some hoops you should be able to install to a custom location by setting `CARGO_HOME` and `RUSTUP_HOME` to the locations you want before running the installer (and when subsequently running cargo/rustup, etc).

Customizing the installation location in a variety of ways is requested a lot, so it'll have to be easier to do eventually.

**Comment by sekhat** [comment]
@brson Cool, I'll give that ago later.

**Comment by sekhat** [comment]
This seems to have done the trick. I'll close it.

**Comment by ehisboy615** [comment]
i need help for this To get started you need Cargo's bin directory (%USERPROFILE%\.cargo\bin) in
your PATH environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.
