### ISSUE TITLE
`rustup show` fails when active toolchain is custom?

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#599]
Create Rustup Toolchain

```
rustup toolchain link ios $HOME/rustc-ios
```

Override current directory toolchain

```
rustup override set ios
```

```
$ rustup show
Default host: x86_64-apple-darwin
error: toolchain 'ios' does not support components
info: caused by: invalid toolchain name: 'ios'
```

[Original Report](http://stackoverflow.com/questions/38466493/unable-to-override-rustup-toolchain-for-custom-build-of-ios-toolchain)

**Comment by inejge** [comment]
Notice that the error "toolchain X does not support components" is _tested for_ in `list_targets_custom_toolchain`, so in #621 I couldn't simply return an empty list from `list_components()`. When trying to list targets, this error has an unfortunate addendum "caused by: invalid toolchain name" -- should we differentiate between a custom toolchain and an invalid name somehow? (That would be a separate issue/PR.)

**Comment by brson** [comment]
@inejge from your current patch in #621 it *looks* like you've solved that question?

**Comment by inejge** [comment]
@brson I have, for `rustup show`; what bothered me was the misleading error message displayed for `rustup target list` when a custom toolchain is active. On second thought, one could argue that anyone working with custom toolchains should know what they're doing, and not be hopelessly confused by that message.

**Comment by brson** [comment]
Fixed!
