### ISSUE TITLE
[Windows 10, Build 14915] rustup-init.exe detected as malware

### ISSUE THREAD

**Issue by Rukenshia** [rust-lang-nursery/rustup.rs#716]
This is the latest Windows Insider build on the fast ring, 14915. The rustup-init.exe file is detected as malware by Windows Defender:

![Windows Defender](http://in.fkn.space/i/757-57d331c91baef.png)

The rustup command fails with os error 225:
```
info: installing component 'cargo'
error: can't open self exe to calculate hash
info: caused by: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (os error 225)
```

**Comment by plast1c** [comment]
Just wanted to confirm I saw tonight as well.  For the record my version of rustup was probably a couple of months old.

**Comment by Rukenshia** [comment]
I just downloaded it from the website again and it seems to work. I had a pretty old version too. Maybe someone else will find this helpful when encountering this.

**Comment by ghost** [comment]
This happens for me on Rust 1.30.0, downloading the `rustup-init.exe` binary in Chrome results in
*Failed - Virus detected*.

I assume Chrome uses AMSI for the virus check on Windows and not a remote service and I have Defender installed by default as I am on Windows, no other A/V, so the false positive must be Defender's.

The above is the case from `rustup-init.exe` as downloaded from `https://win.rustup.rs/`, the binary at `https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe` downloads fine. I found the latter link through the Other Download Options link.

Maybe the problem here is that an executable gets downloaded from a path which doesn't end in EXE extension in the former case and that is considered as a potential attach attempt or something like that.

The two binaries do differ in size though (5 MB vs 18 MB) so it very well may still be the content of the executable too.
