### ISSUE TITLE
The install problem for 'V3 Lite' (Window10 64bit)

### ISSUE THREAD

**Issue by akadark** [rust-lang-nursery/rustup.rs#734]
The Access is denied when I run rustup on the cmd. 

![default](https://cloud.githubusercontent.com/assets/15935262/18812231/a0ee30ae-8308-11e6-94e0-2f5c5ef1d232.JPG)
![2](https://cloud.githubusercontent.com/assets/15935262/18812232/a35ec3f8-8308-11e6-9285-8973faa82b32.JPG)

And this error message occurs when I restart my computer and retry rustup command.
![4](https://cloud.githubusercontent.com/assets/15935262/18812294/785aff08-830a-11e6-94fb-ac485f569c9f.JPG)

I think it is a problem for the V3 Lite(engine version : 2016.09.23.00) program(Korean anti-virus program) Because this problem doesn't occur when I turn off the V3's realtime protection.

**Comment by sanxiyn** [comment]
This seems similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1185756.

In general, if you get Windows error 32 "The process cannot access the file because it is being used by another process", you should retry. "Another process" is usually antivirus, and retry is likely to succeed after antivirus finished scanning the file.
