### ISSUE TITLE
Add an option to skip rust-docs on rust-init (for CI envs)

### ISSUE THREAD

**Issue by gentoo90** [rust-lang-nursery/rustup.rs#747]
In a CI environments `rust-docs` component isn't needed but you cant skip its installation during `rustup-init`.
Add a CLI option `--no-docs` or `--minimal`, or even `--components` with a list of components to install.

**Comment by Diggsey** [comment]
It might be worth borrowing from cargo's features model, and have something like `--no-default-components`, and update the manifest to distinguish between *required* components and *installed by default* components.

**Comment by lilith** [comment]
Docs and manpages are _huge_. Trying to delete them post-install is a moving target. My base docker image is < 300MB, but the Rust layer is 700MB compressed.

**Comment by oherrala** [comment]
Doc installation seems to be off by default now (since Nov'16):

 https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/22

There also seems to be issue #906 about making the docs installed by default but opt-out if needed. And issue #907 about `--minimal` flag to install only required components.

**Comment by Diggsey** [comment]
Closing in favour of above issues

**Comment by Rantanen** [comment]
_Since I just spent a while trying to figure this out and these issues are still dominating Google results, I'll update these with the current status._

Documentation _was_ opt-in in till early 2017, but then they were made required again in March 2017, tracked by #903 in rustup.rs. While that issue wished for "some more options to remove them", that hasn't happened.. yet.

Fortunately #998 seems to have some recent activity towards allowing opt-out for the docs.
