### ISSUE TITLE
No std downloaded for other toolchains than the default

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang-nursery/rustup.rs#754]
I installed `stable` and `nightly`, with the `linux`, `musl` and `windows-gnu` targets. It works fine on stable but fails on nightly with a `no std found` error for `musl` and `windows`. I add to do this:

```
$ rustup default nightly
$ rustup target add <musl, windows>
$ rustup default stable
```

**Comment by Diggsey** [comment]
If you don't specify a toolchain, it will default to the current toolchain (ie. the override for the current directory, or default if no override specified)

To install for a specific toolchain, use `rustup target add <target> --toolchain <toolchain>`

I think this issue is more a problem with discover-ability. While the `--toolchain` option is documented in `rustup target add --help` / `rustup help target add`, it's not documented in `rustup target --help`, and it's not obvious to new users that targets are local to a toolchain to begin with.

**Comment by Yamakaky** [comment]
Ok. At least `rustup update` seems to update all the targets by default
